baseURL: "https://pabitrachowdhury.github.io/"
title: Pabitra Chowdhury
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Teaching
          url: teaching/
          weight: 2
        - name: CV
          url: cv.pdf
          weight: 3
        - name: Contact
          url: contact/
          weight: 4

params:
    description: "PhD Student in Economics at Northeastern."
    author: Pabitra Chowdhury
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pabitra Chowdhury
          subtitle: "I am a Ph.D. student in Economics at **Northeastern University**. I am also a student affiliate at the **Centre for Health Policy & Healthcare Research** at Northeastern. My research interests in health, public and applied microeconomics. I am also interested in studying public programs, aging and retirment research. Before my Ph.D., I worked as a Research Analyst at the International Food Policy Research Institute, New Delhi and Azim Premji University, Bangalore. I also consulted with Sangath-iHEAR on health equity projects."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: CV
              url: cv.pdf
            - name: Contact
              url: contact/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:chowdhury.pa@northeastern.edu
        - name: LinkedIn
          url: https://www.linkedin.com/in/pabitra-chowdhury-54b038138/
        - name: Google Scholar
          url: https://scholar.google.com/
        - name: GitHub
          url: https://github.com/pabitrachowdhury

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Pabitra Chowdhury"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
